apiVersion: v1
kind: Pod
metadata:
  name: pod-db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-container-noticias
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306


      envFrom: #Com esse parâmetro nós podemos referenciar todas as variaveis de um ConfigMap
       - configMapRef: #Qual é o configmap que você quer referenciar?
          name: configmap-db #Nome do ConfigMap que vamos utilizar










# #Usando "env" para definir variaveis de ambiente para o nosso pod
#       env:
#         - name: "MYSQL_ROOT_PASSWORD" #Nome da nossa variavel
#           value: q1w2e3r4 #valor da nossa variavel
#         - name: "MYSQL_DATABASE" #Nome da nossa variavel
#           value: "empresa"
#         - name: "MYSQL_PASSWORD"
#           value: q1w2e3r4

##Vamos utilizar um ConfigMap para isso 