apiVersion: v1
kind: Pod
metadata:
  name: pod-db-noticias
  labels:
    pod-db-noticias: pod-db-noticias
spec:
  containers:
    - name: db-container-noticias
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306