apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template:
    metadata:
      name: pod-sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: container-sistema-noticias
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap-backend
  selector:
    matchLabels:
      app: sistema-noticias
  
  #Agora precisamos definir o serviço que permitira a comunicação com o Pod, que no nosso caso é o NodePorrt
  serviceName: nodeport-pod-sistema-noticias