apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80 #Podemos utilizar a mesma porta do outro NodePort, pois o IP é diferente
      nodePort: 30001
  selector:
    sistema-noticias: sistema-noticias