apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-portal-noticias

spec:
  type: NodePort
  ports:
    - port: 80 #Porta que ele ouve dentro do Cluster
      targetPort: 80 #Porta que ele mandará as requisições
      nodePort: 30000 #Porta que ele escutara no mundo exterior
  selector:
    app: portal-noticias