apiVersion: v1
kind: Pod
metadata:
  name: pod-portal-noticias
  labels:
    portal-noticias: portal-noticias
spec:
  containers:
    - name: container-portal-noticias
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80