apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - name: container-pvc
      image: nginx:latest
      ports:
        containerPort: 80
      volumeMounts:
        - mountPath: /pvc-volume
          name: pvc-volume

  volume:
    - name: pvc-volume

    #Dessa vez vamos usar o persistentVolumeClaim
      persistentVolumeClaim: #Qual é o Claim?
        claimName: persistent-volume-claim #nome do Claim criado no outro arquivo