#Assim como o RS, o Deployment usa outra versão da API
apiVersion: apps/v1

#E também tem um TIPO de recurso exclusivo dele, o Deployment
kind: Deployment

#vamos definir o nome do Deployment
metadata:
  name: pod-sistema-noticias-deployment

spec: #Especificação do nosso Pod
  replicas: 1

  template: #Esse bloco representa as configurações presentes no nosso Pod
    metadata:
      name: pod-sistema-noticias
      labels:
        app: sistema-noticias

#Especificações do container
    spec:
      containers:
        - name: container-sistema-noticias
          image: aluracursos/sistema-noticias:1

          #apontando para o volume
          volumeMounts:
            - mountPath: /backend-volume
              name: backend-volume

          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap-backend
      volumes:
        - name: backend-volume
          hostPath:
            path: /c/Users/joao.mendes/Desktop/Alura/Devops/Kubernetes-Yaml/Manifest/Volumes/backend-volume
            type: Directory #O TYPE DirectOrCreate vai verificar se o diretório já existe, caso não exista ela vai criar
  selector:
    matchLabels:
      app: sistema-noticias