#Assim como o RS, o Deployment usa outra versão da API
apiVersion: apps/v1

#E também tem um TIPO de recurso exclusivo dele, o Deployment
kind: Deployment

#vamos definir o nome do Deployment
metadata:
  name: pod-db-noticias-deployment

spec: #Especificação do nosso Pod
  replicas: 3
  template:
    metadata:
      name: pod-db-noticias
      labels:
        db-noticias: db-noticias

#Especificações do container
    spec:
      containers:
        - name: db-container-noticias
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: configmap-db
  selector:
    matchLabels:
      db-noticias: db-noticias